// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class ProductComment
    {
        public ProductComment()
        {
            PcommentsImgs = new HashSet<PcommentsImg>();
        }

        public int CommentId { get; set; }
        public int OrderId { get; set; }
        public string CommentContent { get; set; }
        public int Score { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual Order Order { get; set; }
        public virtual ICollection<PcommentsImg> PcommentsImgs { get; set; }
    }
}